const GREEN ="#A8DBA8"
const INBOUND_COLOR=  "#A8DBA8";
const OUTBOUND_COLOR= "#0B486B";
const INBOUND_LINE_COLOR = "#93CD20"

const TAB_BAR_COLOR = "#00796B"

const  TAB_BUTTON_ICON_SIZE =25;


export { GREEN ,INBOUND_COLOR ,OUTBOUND_COLOR ,INBOUND_LINE_COLOR ,TAB_BAR_COLOR  , TAB_BUTTON_ICON_SIZE  };